### ISSUE TITLE
该组件无法实现根据data变化异步加载echarts的功能

### ISSUE THREAD

**Issue by realDuang** [dailybird/echarts-vue#1]
![image](https://user-images.githubusercontent.com/17807197/32424314-8991d248-c2e6-11e7-9db1-34bff55188ad.png)
如上图，将该项目的点击事件修改一下，之后运行后点击图框，可以发现vue中的data改变了，但是echarts图表并没有随之变化。

**Comment by dailybird** [comment]
```
let newOption = JSON.parse(JSON.stringify(this.option))
newOption.series[0] = [1,2,3,4,5,6]
this.option = newOption
```
这样写就行了。
`this.option.seriesp[0].data` 这种形式的修改是不能被监听到的。不信可以在 `watch` 中尝试监听一下 `option`。
